from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
from langchain.output_parsers.json import SimpleJsonOutputParser

try:
    from langsmith.run_helpers import get_current_run_tree
except ImportError:
    get_current_run_tree = None

logger = st.logger.get_logger("micronarratives")


def _scenario_to_text(scenario_data) -> str:
    """
    Convert a scenario (dict or str) into clean human-readable text.

    The LLM returns a dict with keys like "Scenario Title",
    "Participant's Vision for Healthcare", and "AI-Generated Scenario".
    We render only the parts the participant needs to read — the title,
    the narrative, and the themes — as plain prose with no JSON or braces.
    If the value is already a plain string, it is returned as-is.

    This is the single source of truth for scenario formatting. review.py
    imports and uses an identical copy so both files stay in sync — if you
    update the logic here, update it there too (or extract to a shared
    utils module).
    """
    if scenario_data is None:
        return ""

    if isinstance(scenario_data, str):
        return scenario_data.strip()

    if not isinstance(scenario_data, dict):
        return str(scenario_data).strip()

    parts = []

    # Title — try top-level first, then inside AI-Generated Scenario block
    title = scenario_data.get("Scenario Title") or scenario_data.get("scenario_title")
    if not title:
        ai_block = scenario_data.get("AI-Generated Scenario", {})
        if isinstance(ai_block, dict):
            title = ai_block.get("Scenario Title") or ai_block.get("scenario_title")
    if title:
        parts.append(f"**{title}**")

    # Narrative and themes from the AI-Generated Scenario block
    ai_block = scenario_data.get("AI-Generated Scenario", {})
    if isinstance(ai_block, dict):
        narrative = ai_block.get("Narrative") or ai_block.get("narrative")
        if narrative:
            parts.append(narrative)
        themes = ai_block.get("Themes") or ai_block.get("themes")
        if themes:
            parts.append(f"*Themes: {themes}*")

    # Fallback: if there was no AI-Generated Scenario block, try common keys
    if len(parts) <= 1:
        for key in ("narrative", "Narrative", "output_scenario", "scenario"):
            value = scenario_data.get(key)
            if value and isinstance(value, str):
                parts.append(value)
                break

    return "\n\n".join(parts) if parts else str(scenario_data)


def generate_summary(llm_prompts, msgs, extraction_chain, testing):
    """
    Generate a dictionary containing a summary of the key points of the conversation.
    The LLM-generated dictionary is not guaranteed to contain the keys specified in the
    configuration file, so this function pulls out the required keys and leaves them
    blank if a corresponding key-value pair was not generated by the LLM as a result of
    the conversation.
    """
    if testing:
        logger.info(
            f"User {st.session_state['participant_id']}: Using testing messages"
        )
        message_history = llm_prompts.one_shot_conversation
    else:
        message_history = msgs

    answer_set = extraction_chain.invoke({"conversation_history": message_history})
    summary_answers = {key: answer_set.get(key, "") for key in llm_prompts.summary_keys}
    st.session_state["summary_answers"] = summary_answers

    return summary_answers


def generate_scenarios(llm_prompts, chat_model, summary_answers, bar):
    """
    Generates the scenarios from the user's summary answers, in the style of each of the
    personas. As scenarios are generated, updates the progress bar.
    """
    scenario_chain = (
        llm_prompts.scenario_prompt_template | chat_model | SimpleJsonOutputParser()
    )

    def generate_single(persona):
        response = scenario_chain.invoke(
            {"persona": persona, "language_level": st.session_state.get("language_level", "intermediate")} | summary_answers
        )
        if not isinstance(response, dict) or "output_scenario" not in response:
            raise ValueError(f"Unexpected response format: {response}")
        # FIX: convert the raw output_scenario value (which may itself be a
        # dict) to a clean plain-text string at generation time, so every
        # downstream consumer (review, rate, adapt, finalise) always receives
        # a str and never a dict.
        return _scenario_to_text(response["output_scenario"])

    scenarios = [None] * len(llm_prompts.personas)
    completed = 0

    with ThreadPoolExecutor(max_workers=min(3, len(llm_prompts.personas))) as executor:
        future_to_index = {
            executor.submit(generate_single, persona): index
            for index, persona in enumerate(llm_prompts.personas)
        }

        for future in as_completed(future_to_index):
            index = future_to_index[future]
            try:
                scenarios[index] = future.result()
            except Exception as exc:
                logger.error(f"Error generating scenario {index}: {exc}")
                scenarios[index] = (
                    "Sorry, something went wrong while generating this scenario."
                )

            completed += 1
            bar.progress(
                completed / len(llm_prompts.personas),
                f"Processed scenario {completed} of {len(llm_prompts.personas)}",
            )

    return scenarios


def generate_scenarios_with_progress(
    llm_prompts,
    chat_model,
    summary_answers,
    langsmith_enabled=False,
):
    """Set up the Streamlit page for scenario generation and return the results."""
    st.markdown("#### Summarising your story")
    messages_container = st.container(border=True)

    with messages_container:
        st.chat_message("ai").write(
            "Seems I have everything! "
            "Let me try to summarise what you said in three scenarios. "
            "See if you like any of these!"
        )
        bar = st.progress(0, text="Processing your scenarios")
        scenarios = generate_scenarios(llm_prompts, chat_model, summary_answers, bar)
        st.session_state["generated_scenarios"] = scenarios

    st.session_state["langsmith_run_id"] = None
    if langsmith_enabled and get_current_run_tree is not None:
        run_tree = get_current_run_tree()
        if run_tree is not None:
            st.session_state["langsmith_run_id"] = run_tree.id

    return scenarios


def select_scenario(index):
    """Store the index of the selected scenario."""
    st.session_state["selected_scenario_index"] = index


def rate_selected_scenario():
    """Display the selected scenario and collect a 0-10 rating."""
    selected_index = st.session_state["selected_scenario_index"]
    # FIX: scenario is already a plain str after _scenario_to_text in
    # generate_single, so this is safe. The explicit str() call below is a
    # belt-and-braces guard against any legacy session state that pre-dates
    # this fix (e.g. a browser tab that was open before the deploy).
    scenario_text = str(st.session_state["generated_scenarios"][selected_index])

    container = st.container(border=True)
    with container:
        # FIX: use st.markdown so bold/italic formatting in scenario_text
        # renders correctly (st.write would stringify a dict visibly).
        st.markdown(scenario_text)
        st.markdown(
            "<div style='font-size:1.5em; font-weight:bold; font-style:italic;'>"
            "How close is this to what I want to say?"
            "</div>",
            unsafe_allow_html=True,
        )
        st.markdown(
            """
            <div
                style="display: flex; justify-content: space-between; margin-top: -8px;"
            >
                <span style="color: red;">needs a lot of work</span>
                <span style="color: green;">this looks good</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

        rating = st.slider(
            "How would you rate this scenario?",
            min_value=0,
            max_value=10,
            value=5,
            step=1,
            label_visibility="collapsed",
            format=" ",
        )
        st.session_state["selected_scenario_review"] = rating

        _, center_col, _ = st.columns([1, 2, 1])
        with center_col:
            if st.button("Continue", use_container_width=True):
                # FIX: always store a plain str so adapt.py's text_area and
                # finalise.py's display never receive a dict.
                st.session_state["final_scenario"] = scenario_text
                st.session_state["final_scenario_editor"] = scenario_text
                if rating == 10:
                    st.session_state["agentState"] = "save"
                else:
                    st.session_state["agentState"] = "adapt"
                st.rerun()


def click_selection_yes(index):
    """Compatibility wrapper for older selection flow."""
    select_scenario(index)


def click_selection_no(index):
    """Compatibility wrapper for older selection flow."""
    st.session_state["scenario_judgement"][index] = ""


def sliderChange(slider_name, index):
    """Compatibility wrapper for older selection flow."""
    st.session_state["scenario_judgement"][index] = st.session_state[slider_name]


def scenario_selection(popover, index):
    """Compatibility wrapper retaining the older popover entry point."""
    with popover:
        st.button(
            "Continue with this scenario 🎉",
            key=f"yeskey_{index}",
            on_click=select_scenario,
            args=(index,),
            use_container_width=True,
        )